### PR TITLE
Issue #3 - Added logo to first slide

### PR DESCRIPTION
**Pull request by EChesters**
Added logo to images folder
Changed placeholder text on the first slide
Removed background colour from images with transparent background

### CODE REVIEW

**Comment by tanyapowell** [comment]
Screengrab please 😄 

Also, all the changes from PR #6 are in this PR. Could you take a lookie look

**Comment by EChesters** [comment]
Screenshot here:
screen shot 2016-04-25 at 18 19 32

Just about to fix the merge conflicts..

**Comment by EChesters** [comment]
I've fixed the conflicts locally, not sure why it's not coming up here. Once the changes have been approved I'll push the fix to `gh-pages` as it suggested in the CMD instructions to fix the conflicts.

**Comment by tanyapowell** [comment]
Did you manually change each theme's css or was it when you changed something in the sass that's caused the update in each theme's css file?

**Pull request merged**
